version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

volumes:
  mongodb-data:

networks:
  backend:
    driver: bridge
